language: cpp
addons:
 apt:
   sources: [ 'ubuntu-toolchain-r-test' ]
   packages:
           - libstdc++-6-dev
compiler: gcc
before_script:
  - sudo apt-get install libboost-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install libspdlog-dev -y
  - sudo apt-get install libdlib-dev
  - sudo apt-get install libopenblas-dev
  - git clone https://github.com/davisking/dlib
  - mkdir build
  - cd build
  - cmake .
  - cmake --build .

script:
- cmake .
- cmake --build .
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uporphyrion:$BINTRAY_API_KEY "https://api.bintray.com/content/porphyrion/otus/otus.lesson.15/$TRAVIS_BUILD_NUMBER/Kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
